### ISSUE TITLE
Compile error with the example in the repository

### ISSUE THREAD

**Issue by renerlemes** [SergiuToporjinschi/settingsmanager#5]
Can anyone help me?

c:/users/rener/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\settingsmanager\main.cpp.o:C:\Program Files (x86)\Arduino\libraries\settingsmanager\src/main.cpp:29: multiple definition of `sm'; sketch\sketch_may06a.ino.cpp.o:C:\Users\Rener\Desktop\sketch_may06a/sketch_may06a.ino:4: first defined here

c:/users/rener/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\settingsmanager\main.cpp.o: in function `loop':

C:\Program Files (x86)\Arduino\libraries\settingsmanager\src/main.cpp:177: multiple definition of `loop'; sketch\sketch_may06a.ino.cpp.o:C:\Users\Rener\Desktop\sketch_may06a/sketch_may06a.ino:11: first defined here

c:/users/rener/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\settingsmanager\main.cpp.o: in function `setup':

C:\Program Files (x86)\Arduino\libraries\settingsmanager\src/main.cpp:160: multiple definition of `setup'; sketch\sketch_may06a.ino.cpp.o:C:\Users\Rener\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266/HardwareSerial.h:76: first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Generic ESP8266 Module

**Comment by SergiuToporjinschi** [comment]
Hi, I think you've updated to the last version. 
I'm trying to migrate this project to platformio. I think you are are using Arduino IDE. 
The last two releases are just some trial and error because I cannot determine if the new file structure is accepted by Arduino. there are no changes in code for this library in last two releases. So I'm commanding you to stay at 2.0.3 version until i'm sure is working fine. 
I will put a message here when is working. 
Is ok for you?
Sergiu

**Comment by renerlemes** [comment]
Of course. I'm waiting. Thank you

**Comment by SergiuToporjinschi** [comment]
or, you can go in library folder in src and remove main.cpp file and should compile, that file is a copy of SettingsManager.ino from examples folder

**Comment by renerlemes** [comment]
If I have the following json:

`
{
"Debug": true,
"Device": [
    {
      "Serial": "AUT010001"
    }
  ],
}
`

How to update the Serial field?

**Comment by SergiuToporjinschi** [comment]
to be honest, I did not test this too much on arrays
